### PR TITLE
fix: dispute query fixes

### LINKED ISSUE #748: team-vote power displaying wrong
./layerd query dispute team-vote 8
team_vote:
  reporter_power: "0"
  vote: 1
  voter_power: "25000000"

Should be 33 not 25

### PR DESCRIPTION
**Pull request by danflo27**
## Description

- `./layerd query dispute team-vote` showed old team voting power
- `./layerd query dispute tally` wasn't getting BlockInfo properly and now shows voting percentages
- added `./layerd query oracle get-total-tips`, get-total-user-tips already exists
- upgraded gov module API to v1 instead of v1beta1 so that proposal summary and more shows on swagger page
- in TallyVote, the scaled support/against/invalid calculations were still dividing by 4. It is just used to check which of the 3 groups is biggest, so no big deal 

## Related Issue

Fixes #748 
#750 
#754 

## Type of Change

- [x] Chain Changes (please describe): execute vote no longer removes blockinfo, SetTeamVote returns 3s instead of 25 now (doesnt get used for any calculations), queries
- [x] Tests

## Testing

unit tests and interchaintest 

## Checklist

- [x] Code follows project style guidelines
- [x] I have added appropriate comments to my code
- [x] I have updated the documentation accordingly
- [x] I have added tests that prove my fix or feature works
- [x] go test ./... is passing locally
- [x] make e2e is passing locally

### CODE REVIEW

File: x/dispute/keeper/query.go [hunk 1]
```diff
@@ -113,51 +115,93 @@ func (k Querier) Tally(ctx context.Context, req *types.QueryDisputesTallyRequest
...
+		userInvalidPerc = (float64(voteCounts.Users.Invalid) / float64(totalUserPower.Uint64())) * 100 / 3
+	} else {
+		userForPerc = 0
+		userAgainstPerc = 0
+		userInvalidPerc = 0
+	}
+
+	// sum up each vote choice total (excluding team for now)
+	combinedTotal := &types.CombinedTotal{
+		Support: uint64(userForPerc + reporterForPerc),
```
Comment (akremstudy) [inline x/dispute/keeper/query.go:148]: do you mean to truncate the decimals here?

Comment (danflo27) [reply x/dispute/keeper/query.go:148]: These should stay floats before the addition good call

**Review by akremstudy — APPROVED** [review]
